[package]
name = "EchelonUSDTStrategy"
version = "1.0.0"
authors = []

[addresses]
echelon_usdt = "0x0"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.Echelon]
local = "./echelon_interface"

[dependencies.Satay]
local = "../../satay"


[dev-dependencies]
